version: "3.7"

services:
    postgres:
        image: postgres:18
        restart: unless-stopped
        dns:
            - 8.8.8.8
            - 1.1.1.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_NAME}
            PGSSLMODE: require
        volumes:
          - postgres_data:/var/lib/postgresql
          - ./dump:/docker-entrypoint-initdb.d
volumes:
  postgres_data: