version: "3.7"

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
          - ./data:/home
          - ./dump:/docker-entrypoint-initdb.d
