version: "3.7"

services:
    postgres:
        image: postgres
        ports:
            - "5439:5439"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
          - ./data:/home