version: "3.7"

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: grappus
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - ./data:/home